// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsZjDaiZeX7vk54Gh6wSlh8TPhzTIEDp0',
    appId: '1:119953377064:web:5fbd697b0e4bd6fcf2f21d',
    messagingSenderId: '119953377064',
    projectId: 'flutter-iot-suhu',
    authDomain: 'flutter-iot-suhu.firebaseapp.com',
    databaseURL: 'https://flutter-iot-suhu-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-iot-suhu.appspot.com',
    measurementId: 'G-6VWS6QB11S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGWEHOMeQjsZVPQW6fZ3gTQGeyCftT9hQ',
    appId: '1:119953377064:android:bbe126984ca6ebd4f2f21d',
    messagingSenderId: '119953377064',
    projectId: 'flutter-iot-suhu',
    databaseURL: 'https://flutter-iot-suhu-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-iot-suhu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzSwt70gWF3iGLTnD3_txzZLNxf4ZVr7c',
    appId: '1:119953377064:ios:cb008ca91d78193cf2f21d',
    messagingSenderId: '119953377064',
    projectId: 'flutter-iot-suhu',
    databaseURL: 'https://flutter-iot-suhu-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-iot-suhu.appspot.com',
    iosClientId: '119953377064-brlfrilupaf1uq9t4baoundtd2pmmrng.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterIotSuhu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzSwt70gWF3iGLTnD3_txzZLNxf4ZVr7c',
    appId: '1:119953377064:ios:cb008ca91d78193cf2f21d',
    messagingSenderId: '119953377064',
    projectId: 'flutter-iot-suhu',
    databaseURL: 'https://flutter-iot-suhu-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-iot-suhu.appspot.com',
    iosClientId: '119953377064-brlfrilupaf1uq9t4baoundtd2pmmrng.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterIotSuhu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsZjDaiZeX7vk54Gh6wSlh8TPhzTIEDp0',
    appId: '1:119953377064:web:1481860c1a4ccaf8f2f21d',
    messagingSenderId: '119953377064',
    projectId: 'flutter-iot-suhu',
    authDomain: 'flutter-iot-suhu.firebaseapp.com',
    databaseURL: 'https://flutter-iot-suhu-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-iot-suhu.appspot.com',
    measurementId: 'G-7567B1D2Z7',
  );
}
